---
  - name: Installing DVWA container
    hosts: webservers
    become: true
    tasks:


    - name: Installing docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Installing python3-pip
      apt:
        name: python3-pip
        state: present
        force_apt_get: yes

    - name: Installing docker
      pip:
        name: docker
        state: present

    - name: Installing dvma container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80
        restart_policy: always

    - name: Enabling docker service
      systemd:
        name: docker
        enabled: yes

