---
- name: Installing Metricbeat and copying configuration
  hosts: webservers
  become: yes
  tasks:

  - name: Downloading Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Installing Metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: Copying & Pasting metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enabling Metricbeat docker mod
    command: metricbeat modules enable docker

  - name: Setting up Metricbeat
    command: metricbeat setup

  - name: Starting Metricbeat
    command: service metricbeat start
